#!/bin/bash
set -e

apt-get clean
apt-get autoclean
apt-get autoremove
rm -f /var/lib/apt/lists/*_*
rm -f /usr/lib/jvm/java-8-oracle/*.zip
rm -f /var/cache/oracle-jdk8-installer/*.tar.gz
rm -Rf /usr/lib/jvm/java-8-oracle/lib/missioncontrol
rm -Rf /usr/lib/jvm/java-8-oracle/lib/visualvm