#!/bin/bash
set -e

rm -f /etc/apt/sources.list.d/webupd8team-java.list

# add repo
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee /etc/apt/sources.list.d/webupd8team-java.list
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list

# accept keys
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886

# install
apt-get update
apt-get install -y oracle-java8-installer || (apt-get -f -y install && apt-get install -y oracle-java8-installer)